### ISSUE TITLE
Linux run failure

### ISSUE THREAD

**Issue by httogo** [RT-Thread/rtthread-pomegranate#5]

**Comment by windchargerj** [comment]
Replace qemu command as follow in **run.sh**.
`${QEMU_RUNTIME} -nographic -smp 2 -machine virt -m 512M -kernel linux-5.12.3/arch/riscv/boot/Image -append "root=/dev/vda rw console=ttyS1,115200n8 earlycon=sbi" -drive file=${ROOT}/output/rootfs.ext4,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 `
